### ISSUE TITLE
Tarea.Infografìa.Matematicas Discretas.Anel Lorely Gonzalez Gonzalez

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/infografia-A-Lorely-Z#1]
[Infografìa.Matemàticas Discretas.Anel Lorely Gonzalez Gonzalez.pdf](https://github.com/user-attachments/files/16735066/Infografia.Matematicas.Discretas.Anel.Lorely.Gonzalez.Gonzalez.pdf)

**Comment by AlynGomez12** [comment]
Redacción y Ortografía:14/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:13/14
Uso de Imágenes y Colores:14/14
Presentación Visual:13/14
Referencias:14/14
Presentación:14/14
Calificación Final: 19.8/20
Falto agregar nombre y grupo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
